dist: trusty
sudo: required 
language: cpp
os:
- linux
branches:
  only:
  - master

install:
- cd $TRAVIS_BUILD_DIR/ci/travis; ./install_googletest.sh;
- cd $TRAVIS_BUILD_DIR/ci/travis; ./install_rapidassist.sh;

script:
- cd $TRAVIS_BUILD_DIR/ci/travis; ./build_library.sh;

after_success:
- cd $TRAVIS_BUILD_DIR/build/bin; ./libmidi_unittest || true; #do not fail build even if a test fails.

notifications:
  email: true
